#!/usr/bin/python

HOSTNM='localhost' # Replace with the network hostname if running externally
PNO='8081'

import requests, json
from pprint import pprint

url='http://'+HOSTNM+':'+PNO+'/api/notebook'
data='''{}'''
response = requests.get(url,data=data)
#ztext=response.text
zjson=response.json()
#print(json.dumps(zjson, indent=4))
pprint(zjson)
