#!/opt/local/bin/python
# runzepp

NOTENM='/00-va-App 0.2.8.7' #Edit Zeppelin note full name with / here
HOSTN='bigva224win.local' #Replace with network hostname if running externally

import requests,json, sys
import time
from datetime import datetime
from pprint import pprint

def getid():
        url='http://bigva224win.local:8081/api/notebook'
        data='''{}'''
        response = requests.get(url,data=data)
        zjson=response.json()
        for i in range(len(zjson['body'])):
                if zjson['body'][i]['path'] == NOTENM:
                        print(NOTENM,'->',zjson['body'][i]['id'])
                        return zjson['body'][i]['id']
def chkzepp(url,data):
	response = requests.get(url,data=data)
	zjson=response.json()
	zstatus=zjson['body']['isRunning']
	return zstatus,zjson # returns True if VA App running otherwise False
####
NOTEID=getid()

# datetime object containing current date and time
now = datetime.now()
print("VA App started:", now)
# dd/mm/YY H:M:S
dt_string = now.strftime("%d-%b-%Y %H:%M:%S")
print(dt_string)	

url='http://bigva224win.local:8081/api/notebook/job/'+NOTEID
data='''{}'''

zcheck,zjson2 = chkzepp(url,data)

if not zcheck:
	response = requests.post(url,data=data)
	zjson=response.json()
	zfjson=json.dumps(zjson, indent=4)
	print(zfjson)
	sys.exit("VA App is Now Running")
else:
	zcheck,zjson2 = chkzepp(url,data)

zlast=len(zjson2['body']['paragraphs'])-1

for i in range (len(zjson2['body']['paragraphs'])):
        if zjson2['body']['paragraphs'][i]['status'] != 'FINISHED':
                print('Paragraph',i+1,zjson2['body']['paragraphs'][i]['status'])
#
# crontab runs at 11:50pm every night
#
# 50 23 * * * /home/saauser/bin/runzepp > /home/saauser/log/va-log.txt 2>&1
